set(LIB_NAME task_js)
set(LIB_PATH ${CMAKE_SOURCE_DIR}/src/task_js)
add_library(${LIB_NAME} INTERFACE)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/js.c)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/JSTask.cpp)
target_include_directories(${LIB_NAME} INTERFACE ${LIB_PATH})
target_link_libraries(${PROJECT_NAME} ${LIB_NAME})