####################################################################################################
# Script that make image of fat from fs folder and generate c file with content
####################################################################################################
CREATE_FILE="src/fs_data.c"
####################################################################################################
# clean stale file
rm -rf $CREATE_FILE
# create new empty
touch $CREATE_FILE
# print content
echo "//--------------------------------------------------------------------------------------------------
// Disc data from fs folder
//--------------------------------------------------------------------------------------------------

// Autogenerated file, do not edit, edit content in fs folder in root of project

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include \"msc/msc_disk.h\"

//--------------------------------------------------------------------------------------------------

// static files
static S_FILE static_files[1] = {
        {
                .name    = \"welcome.txt\",
                .content = \"Hello, World!\r\n\"
        }
};

//--------------------------------------------------------------------------------------------------" > $CREATE_FILE
echo "Data successfully created..."
####################################################################################################