set(LIB_NAME task)
set(LIB_PATH ${CMAKE_SOURCE_DIR}/src/task)
add_library(${LIB_NAME} INTERFACE)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/Task.cpp)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/TaskManager.cpp)
target_include_directories(${LIB_NAME} INTERFACE ${LIB_PATH})
#target_compile_options (${LIB_NAME} INTERFACE -fexceptions)
#target_compile_options (${LIB_NAME} INTERFACE -frtti)
target_link_libraries(${PROJECT_NAME} ${LIB_NAME})