set(LIB_NAME oofatfs)
set(LIB_PATH ${CMAKE_CURRENT_SOURCE_DIR}/oofatfs/src)
add_library(${LIB_NAME} INTERFACE)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/ff.c)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/ffsystem.c)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/ffunicode.c)
target_include_directories(${LIB_NAME} INTERFACE ${LIB_PATH})
target_link_libraries(${PROJECT_NAME} ${LIB_NAME})

set(LIB_NAME vfs_fat)
set(LIB_PATH ${CMAKE_SOURCE_DIR}/src/vfs_fat)
add_library(${LIB_NAME} INTERFACE)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/Device.cpp)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/FlashDisk.cpp)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/RamDisk.cpp)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/FileSystem.cpp)
target_include_directories(${LIB_NAME} INTERFACE ${LIB_PATH})
target_link_libraries(${PROJECT_NAME} ${LIB_NAME})