set(LIB_NAME task_blink)
set(LIB_PATH ${CMAKE_SOURCE_DIR}/src/task_blink)
add_library(${LIB_NAME} INTERFACE)
target_sources(${LIB_NAME} INTERFACE ${LIB_PATH}/BlinkTask.cpp)
target_include_directories(${LIB_NAME} INTERFACE ${LIB_PATH})
target_link_libraries(${PROJECT_NAME} ${LIB_NAME})